### ISSUE TITLE
how dose this can compatible on journal theme's og tag

### ISSUE THREAD

**Issue by ayttk** [p0v1n0m/opencart_multilingual_homepage_meta_tags#1]
how can i fix that. after i apply this extansion.
let the  journal theme's og tag 
<meta property="og:title" content=> same as title
<meta property="og:description" content="" /> same as description

**Comment by p0v1n0m** [comment]
Hi. Do you want to localize og tags from the journal theme or this extension in conflict with your theme?

**Comment by ayttk** [comment]
ah.. sorry.nothing ,this extension is work perfact!

I try to post on the facebook many times. and i found that the facebook cached the title,description.so when i changed the title,description to different language then post again.But its not changed immediately on the facebook.

and seems that mata title and mata description priority higher than og tags title and description.
so its perfact!

thank you.
